# Generated by Django 4.2.3 on 2023-07-12 19:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='profile/')),
                ('about_me', models.TextField()),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_description', models.TextField()),
                ('blog_theme', models.CharField(choices=[('#ff5e3a', 'Laranja'), ('#4caf50', 'Verde'), ('#9c27b0', 'Roxo'), ('#ff9800', 'Amarelo'), ('#2196f3', 'Azul'), ('#e91e63', 'Rosa'), ('#00bcd4', 'Ciano'), ('#8bc34a', 'Verde Claro'), ('#ffc107', 'Amarelo Escuro'), ('#3f51b5', 'Azul Escuro')], max_length=10)),
            ],
        ),
    ]
